---
users:

  # Alice can log in to servers with her own account, or as the privileged sysadm user
  - name: Alice
    key: AAAAC3NzaC1lZDI1NTE5AAAAID2wmSViPXhYY9yjEBnUJJCaV1YBpbKmbIlBzC4EJSj5
    principals: [ alice, sysadm ]

  # Bob may only log in to servers as the unprivileged business-as-usual user
  - name: Bob 
    key: AAAAC3NzaC1lZDI1NTE5AAAAILQ2vgbwJjPqhptlTkr9bTjAkHTdwte98rTDijQ+ygjo
    principals: [ bau ]
